// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: proto/food.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FindOne
type FoodData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protein      float64 `protobuf:"fixed64,3,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat          float64 `protobuf:"fixed64,4,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbohydrate float64 `protobuf:"fixed64,5,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"`
	Category     int64   `protobuf:"varint,6,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *FoodData) Reset() {
	*x = FoodData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodData) ProtoMessage() {}

func (x *FoodData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodData.ProtoReflect.Descriptor instead.
func (*FoodData) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{0}
}

func (x *FoodData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FoodData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FoodData) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *FoodData) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *FoodData) GetCarbohydrate() float64 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *FoodData) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

type FindOneRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *FindOneRequest) Reset() {
	*x = FindOneRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneRequest) ProtoMessage() {}

func (x *FindOneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneRequest.ProtoReflect.Descriptor instead.
func (*FindOneRequest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{1}
}

func (x *FindOneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindOneResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Data   *FoodData `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *FindOneResponse) Reset() {
	*x = FindOneResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindOneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOneResponse) ProtoMessage() {}

func (x *FindOneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOneResponse.ProtoReflect.Descriptor instead.
func (*FindOneResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{2}
}

func (x *FindOneResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FindOneResponse) GetData() *FoodData {
	if x != nil {
		return x.Data
	}
	return nil
}

// ListFoods
type ListFoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFoodsRequest) Reset() {
	*x = ListFoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodsRequest) ProtoMessage() {}

func (x *ListFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodsRequest.ProtoReflect.Descriptor instead.
func (*ListFoodsRequest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{3}
}

type ListFoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FoodList []*FoodData `protobuf:"bytes,2,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`
}

func (x *ListFoodsResponse) Reset() {
	*x = ListFoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodsResponse) ProtoMessage() {}

func (x *ListFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodsResponse.ProtoReflect.Descriptor instead.
func (*ListFoodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{4}
}

func (x *ListFoodsResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListFoodsResponse) GetFoodList() []*FoodData {
	if x != nil {
		return x.FoodList
	}
	return nil
}

// SearchFoods
type SearchFoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SearchFoodsRequest) Reset() {
	*x = SearchFoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoodsRequest) ProtoMessage() {}

func (x *SearchFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoodsRequest.ProtoReflect.Descriptor instead.
func (*SearchFoodsRequest) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{5}
}

func (x *SearchFoodsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchFoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int64       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	FoodList []*FoodData `protobuf:"bytes,2,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`
}

func (x *SearchFoodsResponse) Reset() {
	*x = SearchFoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_food_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoodsResponse) ProtoMessage() {}

func (x *SearchFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_food_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoodsResponse.ProtoReflect.Descriptor instead.
func (*SearchFoodsResponse) Descriptor() ([]byte, []int) {
	return file_proto_food_proto_rawDescGZIP(), []int{6}
}

func (x *SearchFoodsResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SearchFoodsResponse) GetFoodList() []*FoodData {
	if x != nil {
		return x.FoodList
	}
	return nil
}

var File_proto_food_proto protoreflect.FileDescriptor

var file_proto_food_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x46, 0x6f, 0x6f,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f,
	0x74, 0x65, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x74,
	0x65, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x66, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x03, 0x66, 0x61, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79,
	0x64, 0x72, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x61, 0x72,
	0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x24, 0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x4d, 0x0a, 0x0f, 0x46,
	0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x22, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x46, 0x6f, 0x6f, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58,
	0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2b, 0x0a, 0x09, 0x66,
	0x6f, 0x6f, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08,
	0x66, 0x6f, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x5a, 0x0a, 0x13, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x2b, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x46, 0x6f, 0x6f, 0x64,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x32, 0xcd,
	0x01, 0x0a, 0x0b, 0x46, 0x6f, 0x6f, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38,
	0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x12, 0x14, 0x2e, 0x66, 0x6f, 0x6f, 0x64,
	0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x4f, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74,
	0x46, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x16, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e,
	0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x44, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x18, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x53,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46,
	0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_food_proto_rawDescOnce sync.Once
	file_proto_food_proto_rawDescData = file_proto_food_proto_rawDesc
)

func file_proto_food_proto_rawDescGZIP() []byte {
	file_proto_food_proto_rawDescOnce.Do(func() {
		file_proto_food_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_food_proto_rawDescData)
	})
	return file_proto_food_proto_rawDescData
}

var file_proto_food_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_food_proto_goTypes = []interface{}{
	(*FoodData)(nil),            // 0: food.FoodData
	(*FindOneRequest)(nil),      // 1: food.FindOneRequest
	(*FindOneResponse)(nil),     // 2: food.FindOneResponse
	(*ListFoodsRequest)(nil),    // 3: food.ListFoodsRequest
	(*ListFoodsResponse)(nil),   // 4: food.ListFoodsResponse
	(*SearchFoodsRequest)(nil),  // 5: food.SearchFoodsRequest
	(*SearchFoodsResponse)(nil), // 6: food.SearchFoodsResponse
}
var file_proto_food_proto_depIdxs = []int32{
	0, // 0: food.FindOneResponse.data:type_name -> food.FoodData
	0, // 1: food.ListFoodsResponse.food_list:type_name -> food.FoodData
	0, // 2: food.SearchFoodsResponse.food_list:type_name -> food.FoodData
	1, // 3: food.FoodService.FindOne:input_type -> food.FindOneRequest
	3, // 4: food.FoodService.ListFoods:input_type -> food.ListFoodsRequest
	5, // 5: food.FoodService.SearchFoods:input_type -> food.SearchFoodsRequest
	2, // 6: food.FoodService.FindOne:output_type -> food.FindOneResponse
	4, // 7: food.FoodService.ListFoods:output_type -> food.ListFoodsResponse
	6, // 8: food.FoodService.SearchFoods:output_type -> food.SearchFoodsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_food_proto_init() }
func file_proto_food_proto_init() {
	if File_proto_food_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_food_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_food_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_food_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindOneResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_food_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_food_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_food_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_food_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_food_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_food_proto_goTypes,
		DependencyIndexes: file_proto_food_proto_depIdxs,
		MessageInfos:      file_proto_food_proto_msgTypes,
	}.Build()
	File_proto_food_proto = out.File
	file_proto_food_proto_rawDesc = nil
	file_proto_food_proto_goTypes = nil
	file_proto_food_proto_depIdxs = nil
}
