// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Menu struct {
	MenuID    int64     `json:"menu_id"`
	UserID    int64     `json:"user_id"`
	MenuName  string    `json:"menu_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Recipe struct {
	RecipeID  int64          `json:"recipe_id"`
	UserID    int64          `json:"user_id"`
	Content   sql.NullString `json:"content"`
	ImageLink sql.NullString `json:"image_link"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

type RecipeMenu struct {
	ID       int64 `json:"id"`
	RecipeID int64 `json:"recipe_id"`
	MenuID   int64 `json:"menu_id"`
}

type User struct {
	UserID         int64     `json:"user_id"`
	NickName       string    `json:"nick_name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
