// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: services/menu/proto/menu.proto

package proto

import (
	proto "github.com/moromin/PFC-balancer/services/recipe/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// food
type Food struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protein      float64 `protobuf:"fixed64,3,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat          float64 `protobuf:"fixed64,4,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbohydrate float64 `protobuf:"fixed64,5,opt,name=carbohydrate,proto3" json:"carbohydrate,omitempty"`
	Category     int64   `protobuf:"varint,6,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *Food) Reset() {
	*x = Food{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Food) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Food) ProtoMessage() {}

func (x *Food) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Food.ProtoReflect.Descriptor instead.
func (*Food) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{0}
}

func (x *Food) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Food) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Food) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *Food) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *Food) GetCarbohydrate() float64 {
	if x != nil {
		return x.Carbohydrate
	}
	return 0
}

func (x *Food) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

type FindFoodByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindFoodByIdRequest) Reset() {
	*x = FindFoodByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFoodByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFoodByIdRequest) ProtoMessage() {}

func (x *FindFoodByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFoodByIdRequest.ProtoReflect.Descriptor instead.
func (*FindFoodByIdRequest) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{1}
}

func (x *FindFoodByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindFoodByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *FindFoodByIdResponse) Reset() {
	*x = FindFoodByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindFoodByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindFoodByIdResponse) ProtoMessage() {}

func (x *FindFoodByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindFoodByIdResponse.ProtoReflect.Descriptor instead.
func (*FindFoodByIdResponse) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{2}
}

func (x *FindFoodByIdResponse) GetFood() *Food {
	if x != nil {
		return x.Food
	}
	return nil
}

type ListFoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListFoodsRequest) Reset() {
	*x = ListFoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodsRequest) ProtoMessage() {}

func (x *ListFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodsRequest.ProtoReflect.Descriptor instead.
func (*ListFoodsRequest) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{3}
}

type ListFoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodList []*Food `protobuf:"bytes,1,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`
}

func (x *ListFoodsResponse) Reset() {
	*x = ListFoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFoodsResponse) ProtoMessage() {}

func (x *ListFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFoodsResponse.ProtoReflect.Descriptor instead.
func (*ListFoodsResponse) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{4}
}

func (x *ListFoodsResponse) GetFoodList() []*Food {
	if x != nil {
		return x.FoodList
	}
	return nil
}

type SearchFoodsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *SearchFoodsRequest) Reset() {
	*x = SearchFoodsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFoodsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoodsRequest) ProtoMessage() {}

func (x *SearchFoodsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoodsRequest.ProtoReflect.Descriptor instead.
func (*SearchFoodsRequest) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{5}
}

func (x *SearchFoodsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SearchFoodsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodList []*Food `protobuf:"bytes,1,rep,name=food_list,json=foodList,proto3" json:"food_list,omitempty"`
}

func (x *SearchFoodsResponse) Reset() {
	*x = SearchFoodsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchFoodsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFoodsResponse) ProtoMessage() {}

func (x *SearchFoodsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFoodsResponse.ProtoReflect.Descriptor instead.
func (*SearchFoodsResponse) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{6}
}

func (x *SearchFoodsResponse) GetFoodList() []*Food {
	if x != nil {
		return x.FoodList
	}
	return nil
}

// recipe
type CreateRecipeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FoodAmounts []*proto.FoodAmount `protobuf:"bytes,2,rep,name=food_amounts,json=foodAmounts,proto3" json:"food_amounts,omitempty"`
	Procedures  []string            `protobuf:"bytes,3,rep,name=procedures,proto3" json:"procedures,omitempty"`
	UserId      int64               `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateRecipeRequest) Reset() {
	*x = CreateRecipeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeRequest) ProtoMessage() {}

func (x *CreateRecipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeRequest.ProtoReflect.Descriptor instead.
func (*CreateRecipeRequest) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{7}
}

func (x *CreateRecipeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRecipeRequest) GetFoodAmounts() []*proto.FoodAmount {
	if x != nil {
		return x.FoodAmounts
	}
	return nil
}

func (x *CreateRecipeRequest) GetProcedures() []string {
	if x != nil {
		return x.Procedures
	}
	return nil
}

func (x *CreateRecipeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateRecipeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateRecipeResponse) Reset() {
	*x = CreateRecipeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecipeResponse) ProtoMessage() {}

func (x *CreateRecipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecipeResponse.ProtoReflect.Descriptor instead.
func (*CreateRecipeResponse) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{8}
}

func (x *CreateRecipeResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindRecipeByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *FindRecipeByIdRequest) Reset() {
	*x = FindRecipeByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRecipeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecipeByIdRequest) ProtoMessage() {}

func (x *FindRecipeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecipeByIdRequest.ProtoReflect.Descriptor instead.
func (*FindRecipeByIdRequest) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{9}
}

func (x *FindRecipeByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindRecipeByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipe *proto.Recipe `protobuf:"bytes,1,opt,name=recipe,proto3" json:"recipe,omitempty"`
}

func (x *FindRecipeByIdResponse) Reset() {
	*x = FindRecipeByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindRecipeByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRecipeByIdResponse) ProtoMessage() {}

func (x *FindRecipeByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRecipeByIdResponse.ProtoReflect.Descriptor instead.
func (*FindRecipeByIdResponse) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{10}
}

func (x *FindRecipeByIdResponse) GetRecipe() *proto.Recipe {
	if x != nil {
		return x.Recipe
	}
	return nil
}

type ListRecipesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListRecipesRequest) Reset() {
	*x = ListRecipesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesRequest) ProtoMessage() {}

func (x *ListRecipesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesRequest.ProtoReflect.Descriptor instead.
func (*ListRecipesRequest) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{11}
}

type ListRecipesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Recipes []*proto.Recipe `protobuf:"bytes,1,rep,name=recipes,proto3" json:"recipes,omitempty"`
}

func (x *ListRecipesResponse) Reset() {
	*x = ListRecipesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_menu_proto_menu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListRecipesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipesResponse) ProtoMessage() {}

func (x *ListRecipesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_menu_proto_menu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipesResponse.ProtoReflect.Descriptor instead.
func (*ListRecipesResponse) Descriptor() ([]byte, []int) {
	return file_services_menu_proto_menu_proto_rawDescGZIP(), []int{12}
}

func (x *ListRecipesResponse) GetRecipes() []*proto.Recipe {
	if x != nil {
		return x.Recipes
	}
	return nil
}

var File_services_menu_proto_menu_proto protoreflect.FileDescriptor

var file_services_menu_proto_menu_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x65, 0x6e, 0x75, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x22, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x04, 0x46, 0x6f, 0x6f,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x74, 0x65, 0x69, 0x6e, 0x12,
	0x10, 0x0a, 0x03, 0x66, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x66, 0x61,
	0x74, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79, 0x64, 0x72, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x63, 0x61, 0x72, 0x62, 0x6f, 0x68, 0x79,
	0x64, 0x72, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x22, 0x25, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6f, 0x6f, 0x64, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x14, 0x46, 0x69, 0x6e, 0x64,
	0x46, 0x6f, 0x6f, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1e, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64,
	0x22, 0x12, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x66, 0x6f, 0x6f,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d,
	0x65, 0x6e, 0x75, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x4c, 0x69,
	0x73, 0x74, 0x22, 0x28, 0x0a, 0x12, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x13,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x46, 0x6f,
	0x6f, 0x64, 0x52, 0x08, 0x66, 0x6f, 0x6f, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x99, 0x01, 0x0a,
	0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x66, 0x6f, 0x6f, 0x64,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x52, 0x0b, 0x66, 0x6f, 0x6f, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x73, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x27, 0x0a, 0x15, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x16, 0x46, 0x69, 0x6e,
	0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x63,
	0x69, 0x70, 0x65, 0x52, 0x06, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3f, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x07, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x73, 0x32, 0xcd, 0x04, 0x0a, 0x0b, 0x4d, 0x65, 0x6e, 0x75, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x5f, 0x0a, 0x0c, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6f, 0x6f, 0x64, 0x42, 0x79,
	0x49, 0x64, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6f,
	0x6f, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x46, 0x6f, 0x6f, 0x64, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x12, 0x12, 0x10, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x2f, 0x7b,
	0x69, 0x64, 0x7d, 0x12, 0x51, 0x0a, 0x09, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73,
	0x12, 0x16, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x6d, 0x65, 0x6e, 0x75,
	0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x65, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x46, 0x6f, 0x6f, 0x64, 0x73, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x53, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x46, 0x6f, 0x6f, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x46, 0x6f, 0x6f,
	0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x1b, 0x12, 0x19, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x73, 0x2f,
	0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x2f, 0x7b, 0x6e, 0x61, 0x6d, 0x65, 0x7d, 0x12, 0x5f, 0x0a,
	0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x12, 0x19, 0x2e,
	0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x0d, 0x2f, 0x6d,
	0x65, 0x6e, 0x75, 0x2f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x3a, 0x01, 0x2a, 0x12, 0x67,
	0x0a, 0x0e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x1b, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x14, 0x12, 0x12, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x59, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x6d, 0x65, 0x6e, 0x75, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x63, 0x69,
	0x70, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x15, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0f, 0x12, 0x0d, 0x2f, 0x6d, 0x65, 0x6e, 0x75, 0x2f, 0x72, 0x65, 0x63, 0x69, 0x70,
	0x65, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x6f, 0x72, 0x6f, 0x6d, 0x69, 0x6e, 0x2f, 0x50, 0x46, 0x43, 0x2d, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x6d,
	0x65, 0x6e, 0x75, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_services_menu_proto_menu_proto_rawDescOnce sync.Once
	file_services_menu_proto_menu_proto_rawDescData = file_services_menu_proto_menu_proto_rawDesc
)

func file_services_menu_proto_menu_proto_rawDescGZIP() []byte {
	file_services_menu_proto_menu_proto_rawDescOnce.Do(func() {
		file_services_menu_proto_menu_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_menu_proto_menu_proto_rawDescData)
	})
	return file_services_menu_proto_menu_proto_rawDescData
}

var file_services_menu_proto_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_services_menu_proto_menu_proto_goTypes = []interface{}{
	(*Food)(nil),                   // 0: menu.Food
	(*FindFoodByIdRequest)(nil),    // 1: menu.FindFoodByIdRequest
	(*FindFoodByIdResponse)(nil),   // 2: menu.FindFoodByIdResponse
	(*ListFoodsRequest)(nil),       // 3: menu.ListFoodsRequest
	(*ListFoodsResponse)(nil),      // 4: menu.ListFoodsResponse
	(*SearchFoodsRequest)(nil),     // 5: menu.SearchFoodsRequest
	(*SearchFoodsResponse)(nil),    // 6: menu.SearchFoodsResponse
	(*CreateRecipeRequest)(nil),    // 7: menu.CreateRecipeRequest
	(*CreateRecipeResponse)(nil),   // 8: menu.CreateRecipeResponse
	(*FindRecipeByIdRequest)(nil),  // 9: menu.FindRecipeByIdRequest
	(*FindRecipeByIdResponse)(nil), // 10: menu.FindRecipeByIdResponse
	(*ListRecipesRequest)(nil),     // 11: menu.ListRecipesRequest
	(*ListRecipesResponse)(nil),    // 12: menu.ListRecipesResponse
	(*proto.FoodAmount)(nil),       // 13: recipe.FoodAmount
	(*proto.Recipe)(nil),           // 14: recipe.Recipe
}
var file_services_menu_proto_menu_proto_depIdxs = []int32{
	0,  // 0: menu.FindFoodByIdResponse.food:type_name -> menu.Food
	0,  // 1: menu.ListFoodsResponse.food_list:type_name -> menu.Food
	0,  // 2: menu.SearchFoodsResponse.food_list:type_name -> menu.Food
	13, // 3: menu.CreateRecipeRequest.food_amounts:type_name -> recipe.FoodAmount
	14, // 4: menu.FindRecipeByIdResponse.recipe:type_name -> recipe.Recipe
	14, // 5: menu.ListRecipesResponse.recipes:type_name -> recipe.Recipe
	1,  // 6: menu.MenuService.FindFoodById:input_type -> menu.FindFoodByIdRequest
	3,  // 7: menu.MenuService.ListFoods:input_type -> menu.ListFoodsRequest
	5,  // 8: menu.MenuService.SearchFoods:input_type -> menu.SearchFoodsRequest
	7,  // 9: menu.MenuService.CreateRecipe:input_type -> menu.CreateRecipeRequest
	9,  // 10: menu.MenuService.FindRecipeById:input_type -> menu.FindRecipeByIdRequest
	11, // 11: menu.MenuService.ListRecipes:input_type -> menu.ListRecipesRequest
	2,  // 12: menu.MenuService.FindFoodById:output_type -> menu.FindFoodByIdResponse
	4,  // 13: menu.MenuService.ListFoods:output_type -> menu.ListFoodsResponse
	6,  // 14: menu.MenuService.SearchFoods:output_type -> menu.SearchFoodsResponse
	8,  // 15: menu.MenuService.CreateRecipe:output_type -> menu.CreateRecipeResponse
	10, // 16: menu.MenuService.FindRecipeById:output_type -> menu.FindRecipeByIdResponse
	12, // 17: menu.MenuService.ListRecipes:output_type -> menu.ListRecipesResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_services_menu_proto_menu_proto_init() }
func file_services_menu_proto_menu_proto_init() {
	if File_services_menu_proto_menu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_menu_proto_menu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Food); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFoodByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindFoodByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListFoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFoodsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchFoodsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecipeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRecipeByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindRecipeByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_menu_proto_menu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListRecipesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_menu_proto_menu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_menu_proto_menu_proto_goTypes,
		DependencyIndexes: file_services_menu_proto_menu_proto_depIdxs,
		MessageInfos:      file_services_menu_proto_menu_proto_msgTypes,
	}.Build()
	File_services_menu_proto_menu_proto = out.File
	file_services_menu_proto_menu_proto_rawDesc = nil
	file_services_menu_proto_menu_proto_goTypes = nil
	file_services_menu_proto_menu_proto_depIdxs = nil
}
