// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	ListUsers(ctx context.Context) ([]User, error)
	Store(ctx context.Context, arg StoreParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
